
package ComboBox;

import javax.swing.JComboBox;

public class ComboBoxSuggestionCountry<E>  extends JComboBox<E>{

    public ComboBoxSuggestionCountry() {
        setUI(new ComboSuggestionUI());
        addItem((E) "Afghanistan");
        addItem((E) "Albania");
        addItem((E) "Algeria");
        addItem((E) "Andorra");
        addItem((E) "Angola");
        addItem((E) "Antigua and Barbuda");
        addItem((E) "Argentina");
        addItem((E) "Armenia");
        addItem((E) "Australia");
        addItem((E) "Austria");
        addItem((E) "Azerbaijan");
        addItem((E) "The Bahamas");
        addItem((E) "Bahrain");
        addItem((E) "Bangladesh");
        addItem((E) "Barbados");
        addItem((E) "Belarus");
        addItem((E) "Belgium");
        addItem((E) "Belize");
        addItem((E) "Benin");
        addItem((E) "Bhutan");
        addItem((E) "Bolivia");
        addItem((E) "Bosnia and Herzegovina");
        addItem((E) "Botswana");
        addItem((E) "Brazil");
        addItem((E) "Brunei");
        addItem((E) "Bulgaria");
        addItem((E) "Burkina Faso");
        addItem((E) "Burundi");
        addItem((E) "Cambodia");
        addItem((E) "Cameroon");
        addItem((E) "Canada");
        addItem((E) "Cape Verde");
        addItem((E) "Central African Republic");
        addItem((E) "Chad");
        addItem((E) "Chile");
        addItem((E) "China");
        addItem((E) "Colombia");
        addItem((E) "Comoros");
        addItem((E) "Congo, Republic of the");
        addItem((E) "Congo, Democratic Republic of the");
        addItem((E) "Costa Rica");
        addItem((E) "Cote d'Ivoire");
        addItem((E) "Croatia");
        addItem((E) "Cuba");
        addItem((E) "Cyprus");
        addItem((E) "Czech Republic");
        addItem((E) "Denmark");
        addItem((E) "Djibouti");
        addItem((E) "Dominica");
        addItem((E) "Dominican Republic");
        addItem((E) "East Timor (Timor-Leste)");
        addItem((E) "Ecuador");
        addItem((E) "Egypt");
        addItem((E) "El Salvador");
        addItem((E) "Equatorial Guinea");
        addItem((E) "Eritrea");
        addItem((E) "Estonia");
        addItem((E) "Ethiopia");
        addItem((E) "Fiji");
        addItem((E) "Finland");
        addItem((E) "France");
        addItem((E) "Gabon");
        addItem((E) "The Gambia");
        addItem((E) "Georgia");
        addItem((E) "Germany");
        addItem((E) "Ghana");
        addItem((E) "Greece");
        addItem((E) "Grenada");
        addItem((E) "Guatemala");
        addItem((E) "Guinea");
        addItem((E) "Guinea-Bissau");
        addItem((E) "Guyana");
        addItem((E) "Haiti");
        addItem((E) "Honduras");
        addItem((E) "Hungary");
        addItem((E) "Iceland");
        addItem((E) "India");
        addItem((E) "Indonesia");
        addItem((E) "Iran");
        addItem((E) "Iraq");
        addItem((E) "Ireland");
        addItem((E) "Israel");
        addItem((E) "Italy");
        addItem((E) "Jamaica");
        addItem((E) "Japan");
        addItem((E) "Jordan");
        addItem((E) "Kazakhstan");
        addItem((E) "Kenya");
        addItem((E) "Kiribati");
        addItem((E) "Korea, North");
        addItem((E) "Korea, South");
        addItem((E) "Kosovo");
        addItem((E) "Kuwait");
        addItem((E) "Kyrgyzstan");
        addItem((E) "Laos");
        addItem((E) "Latvia");
        addItem((E) "Lebanon");
        addItem((E) "Lesotho");
        addItem((E) "Liberia");
        addItem((E) "Libya");
        addItem((E) "Liechtenstein");
        addItem((E) "Lithuania");
        addItem((E) "Luxembourg");
        addItem((E) "Macedonia");
        addItem((E) "Madagascar");
        addItem((E) "Malawi");
        addItem((E) "Malaysia");
        addItem((E) "Maldives");
        addItem((E) "Mali");
        addItem((E) "Malta");
        addItem((E) "Marshall Islands");
        addItem((E) "Mauritania");
        addItem((E) "Mauritius");
        addItem((E) "Mexico");
        addItem((E) "Federated States of Micronesia");
        addItem((E) "Moldova");
        addItem((E) "Monaco");
        addItem((E) "Mongolia");
        addItem((E) "Montenegro");
        addItem((E) "Morocco");
        addItem((E) "Mozambique");
        addItem((E) "Myanmar (Burma)");
        addItem((E) "Namibia");
        addItem((E) "Nauru");
        addItem((E) "Nepal");
        addItem((E) "Netherlands");
        addItem((E) "New Zealand");
        addItem((E) "Nicaragua");
        addItem((E) "Niger");
        addItem((E) "Nigeria");
        addItem((E) "Norway");
        addItem((E) "Oman");
        addItem((E) "Pakistan");
        addItem((E) "Palau");
        addItem((E) "Panama");
        addItem((E) "Papua New Guinea");
        addItem((E) "Paraguay");
        addItem((E) "Peru");
        addItem((E) "Philippines");
        addItem((E) "Poland");
        addItem((E) "Portugal");
        addItem((E) "Qatar");
        addItem((E) "Romania");
        addItem((E) "Russia");
        addItem((E) "Rwanda");
        addItem((E) "Saint Kitts and Nevis");
        addItem((E) "Saint Lucia");
        addItem((E) "Saint Vincent and the Grenadines");
        addItem((E) "Samoa");
        addItem((E) "San Marino");
        addItem((E) "Sao Tome and Principe");
        addItem((E) "Saudi Arabia");
        addItem((E) "Senegal");
        addItem((E) "Serbia");
        addItem((E) "Seychelles");
        addItem((E) "Sierra Leone");
        addItem((E) "Singapore");
        addItem((E) "Slovakia");
        addItem((E) "Slovenia");
        addItem((E) "Solomon Islands");
        addItem((E) "Somalia");
        addItem((E) "South Africa");
        addItem((E) "South Sudan");
        addItem((E) "Spain");
        addItem((E) "Sri Lanka");
        addItem((E) "Sudan");
        addItem((E) "Suriname");
        addItem((E) "Swaziland");
        addItem((E) "Sweden");
        addItem((E) "Switzerland");
        addItem((E) "Syria");
        addItem((E) "Taiwan");
        addItem((E) "Tajikistan");
        addItem((E) "Tanzania");
        addItem((E) "Thailand");
        addItem((E) "Togo");
        addItem((E) "Tonga");
        addItem((E) "Trinidad and Tobago");
        addItem((E) "Tunisia");
        addItem((E) "Turkey");
        addItem((E) "Turkmenistan");
        addItem((E) "Tuvalu");
        addItem((E) "Uganda");
        addItem((E) "Ukraine");
        addItem((E) "United Arab Emirates");
        addItem((E) "United Kingdom");
        addItem((E) "United States of America");
        addItem((E) "Uruguay");
        addItem((E) "Uzbekistan");
        addItem((E) "Vanuatu");
        addItem((E) "Vatican City (Holy See)");
        addItem((E) "Venezuela");
        addItem((E) "Vietnam");
        addItem((E) "Yemen");
        addItem((E) "Zambia");
        addItem((E) "Zimbabwe");
    }

    @Override
    public final void addItem(E item) {
        super.addItem(item);
    }
    
    
}
